name: Number set Calculator CI/CD technicalDebt/StaticCodeAnalysis pipeline

on:
  push:
    branches:
      - technicalDebt/StaticCodeAnalysis

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Static code analysis
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build project with Maven
        run: mvn -B package --file pom.xml